/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { PatientsListSchema } from "../../backend/src/patients/patients.router";

const appRouter = t.router({
  patients: t.router({
    getAll: publicProcedure
      .output(PatientsListSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    init: publicProcedure
      .output(PatientsListSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    reset: publicProcedure
      .input(z
  .object({ count: z.number().int().positive().max(200).optional() })
  .optional())
      .output(PatientsListSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    addNew: publicProcedure
      .input(z
  .object({ count: z.number().int().positive().max(200).optional() })
  .optional())
      .output(PatientsListSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
